python train.py \
  --mode 'eca_kpcn' \
  --input_channels 34 \
  --hidden_channels 100 \
  --num_layer 9 \
  --do_val \
  --do_early_stopping \
  --lr 1e-4 \
  --epochs 60 \
  --loss 'L1' \
  --data_dir '/root/kpcn_data/kpcn_data/data'